### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by OswaldoBornemann** [geneing/WaveRNN-Pytorch#1]
Could you share the `tts_metadata.csv` example in `dataset.py`? Cause when i preprocessed my own dataset, and ran the `train.py`, it just show `IndexError: list index out of range`

```
saving model....
Saved checkpoint: checkpoints/checkpoint_step000000000.pth
Traceback (most recent call last):
  File "train.py", line 438, in <module>
    train_loop(device, model, data_loader, optimizer, checkpoint_dir)
  File "train.py", line 303, in train_loop
    for i, (x, m, y) in enumerate(tqdm(data_loader)):
  File "/home/data/anaconda3/envs/mozilla_tts/lib/python3.6/site-packages/tqdm-4.31.1-py3.6.egg/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/home/data/anaconda3/envs/mozilla_tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/data/anaconda3/envs/mozilla_tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/data/anaconda3/envs/mozilla_tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/data/anaconda3/envs/mozilla_tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/data/peter/WaveRNN-Pytorch/dataset.py", line 77, in __getitem__
    m = np.load(entry[2].strip())
IndexError: list index out of range
```

**Comment by geneing** [comment]
I'll provide better instructions soon. 
I use TTS extract_features to prep data. Command line is like this:

python3 extract_features.py --config config.json --data_path /data/M-AILABS/mary_ann --cache_path /data/M-AILABS/mary_ann_cache --num_proc 32 --dataset mailabs --val_split 1000 --process_audio True  --meta_file /data/M-AILABS/mary_ann/metadata.csv

Then I run WaveRNN training: python3 train.py  /data/M-AILABS/mary_ann_cache

I'm still in the process of training with TTS matching params. I'll post pretrained weights when I'm done.

**Comment by OswaldoBornemann** [comment]
@geneing thanks my friend. Everything is working now.
